export const ADD_DICTIONARY = 'ADD_DICTIONARY';
export const VALIDATE_DICTIONARY = 'VALIDATE_DICTIONARY';
export const UPDATE_DICTIONARY = 'UPDATE_DICTIONARY';
export const DELETE_DICTIONARY = 'DELETE_DICTIONARY';

